name: MCManhunt
main: com.justinhwang.mcmanhunt.MCManhunt
version: 1.0.0
api-version: 1.16
commands:
  manhunt:
    permission: mcmanhunt
    description: manage the manhunt plugin (enable/disable)
    aliases:
      - mcmanhunt
  compass:
    permission: mcmanhunt.compass
    description: gives the player a tracking compass
    aliases:
      - tracker
      - playertracker
      - playercompass
  setoverworld:
    permission: mcmanhunt
    description: set the world that the minigame is occurring in
    aliases:
      - setmanhuntoverworld
      - setmanhuntworld
  hunters:
    permission: mcmanhunt
    description: manage the hunters
    aliases:
      - chasers
      - hunter
      - chaser
  runner:
    permission: mcmanhunt
    description: set the speedrunner
    aliases:
      - speedrunner
      - setspeedrunner
      - setrunner

permissions:
  mcmanhunt:
    description: allows the user to change settings in the MCManhunt plugin
    default: op
  mcmanhunt.compass:
    description: allows the user to give themselves a compass
    default: op